// wrappers/svelte/TexGen.svelte
<script>
    import { onMount, onDestroy } from 'svelte';
    import TexGen from '../../texgen.js';

    export let shader;
    export let compressed = false;
    export let animated = false;
    export let uniforms = {};
    export let width = 512;
    export let height = 512;
    export let style = "";

    let canvas;
    let tg;
    let reqId;

    $: if (tg && !animated) {
        tg.render(0, uniforms);
    }

    onMount(() => {
        tg = new TexGen({ canvas, width, height });
        const sourceCode = compressed ? TexGen.decompress(shader) : shader;
        
        if (!sourceCode || !tg.init(sourceCode)) {
            console.error("TexGen Svelte: Failed to initialize shader");
            return;
        }

        if (animated) {
            const loop = () => {
                tg.render(performance.now() / 1000, uniforms);
                reqId = requestAnimationFrame(loop);
            };
            loop();
        } else {
            tg.render(0, uniforms);
        }
    });

    onDestroy(() => {
        if (reqId) cancelAnimationFrame(reqId);
    });
</script>

<canvas bind:this={canvas} {style}></canvas>

// wrappers/react/TexGen.jsx
import React, { useRef, useEffect } from 'react';
import TexGen from '../../texgen.js';

export default function TexGenComponent({ 
  shader, 
  compressed = false, 
  animated = false, 
  uniforms = {}, 
  width = 512, 
  height = 512, 
  style = {} 
}) {
  const canvasRef = useRef(null);
  const tgRef = useRef(null);
  const reqRef = useRef(null);

  useEffect(() => {
    if (!canvasRef.current) return;

    tgRef.current = new TexGen({ canvas: canvasRef.current, width, height });
    
    const sourceCode = compressed ? TexGen.decompress(shader) : shader;
    if (!sourceCode || !tgRef.current.init(sourceCode)) {
      console.error("TexGen React: Failed to initialize shader");
      return;
    }

    if (animated) {
      const animate = () => {
        tgRef.current.render(performance.now() / 1000, uniforms);
        reqRef.current = requestAnimationFrame(animate);
      };
      animate();
    } else {
      tgRef.current.render(0, uniforms);
    }

    return () => {
      if (reqRef.current) cancelAnimationFrame(reqRef.current);
    };
  }, [shader, compressed, animated, uniforms, width, height]);

  return <canvas ref={canvasRef} style={style} />;
}
