// wrappers/vue/TexGen.vue
<template>
  <canvas ref="canvas" :style="customStyle"></canvas>
</template>

<script>
import TexGen from '../../texgen.js';

export default {
  name: 'TexGen',
  props: {
    shader: { type: String, required: true },
    compressed: { type: Boolean, default: false },
    animated: { type: Boolean, default: false },
    uniforms: { type: Object, default: () => ({}) },
    width: { type: Number, default: 512 },
    height: { type: Number, default: 512 },
    customStyle: { type: Object, default: () => ({}) }
  },
  data() {
    return {
      tg: null,
      reqId: null
    };
  },
  mounted() {
    this.initTexGen();
  },
  beforeDestroy() {
    if (this.reqId) cancelAnimationFrame(this.reqId);
  },
  watch: {
    shader: 'initTexGen',
    uniforms: {
      deep: true,
      handler() {
        if (!this.animated && this.tg) {
          this.tg.render(0, this.uniforms);
        }
      }
    }
  },
  methods: {
    initTexGen() {
      if (this.reqId) cancelAnimationFrame(this.reqId);

      this.tg = new TexGen({ canvas: this.$refs.canvas, width: this.width, height: this.height });
      const sourceCode = this.compressed ? TexGen.decompress(this.shader) : this.shader;
      
      if (!sourceCode || !this.tg.init(sourceCode)) {
        console.error("TexGen Vue: Failed to initialize shader");
        return;
      }

      if (this.animated) {
        const animate = () => {
          this.tg.render(performance.now() / 1000, this.uniforms);
          this.reqId = requestAnimationFrame(animate);
        };
        animate();
      } else {
        this.tg.render(0, this.uniforms);
      }
    }
  }
}
</script>

// wrappers/svelte/TexGen.svelte
<script>
    import { onMount, onDestroy } from 'svelte';
    import TexGen from '../../texgen.js';

    export let shader;
    export let compressed = false;
    export let animated = false;
    export let uniforms = {};
    export let width = 512;
    export let height = 512;
    export let style = "";

    let canvas;
    let tg;
    let reqId;

    $: if (tg && !animated) {
        tg.render(0, uniforms);
    }

    onMount(() => {
        tg = new TexGen({ canvas, width, height });
        const sourceCode = compressed ? TexGen.decompress(shader) : shader;
        
        if (!sourceCode || !tg.init(sourceCode)) {
            console.error("TexGen Svelte: Failed to initialize shader");
            return;
        }

        if (animated) {
            const loop = () => {
                tg.render(performance.now() / 1000, uniforms);
                reqId = requestAnimationFrame(loop);
            };
            loop();
        } else {
            tg.render(0, uniforms);
        }
    });

    onDestroy(() => {
        if (reqId) cancelAnimationFrame(reqId);
    });
</script>

<canvas bind:this={canvas} {style}></canvas>
